config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount ActionCable.server => '/cable'
  get "(/:locale)/userlogin", to: "lines#user_login", as: :user_login
  get '/redirect', to: 'function_redirects#redirect', as: :function_redirect

  scope module: :lines, path: :lines, as: :lines do
    # customer sesson new
    get "/identify_shop_customer/(:social_service_user_id)", action: "identify_shop_customer", as: :identify_shop_customer
    # customer sesson create
    post :customer_sign_in
    get "/contacts/social_service_user_id/:encrypted_social_service_user_id", action: "contacts", as: :contacts
    post :make_contact
    get :identify_code
    get :ask_identification_code
    put :update_customer_address

    scope module: :verification, path: :verification, as: :verification do
      get "/:encrypted_social_service_user_id", action: "show"
      get "/message_api_status/:encrypted_social_service_user_id", action: "message_api_status", as: :message_api_status
    end

    scope module: :customers, path: :customers, as: :customers do
      resources :online_service_purchases, only: [:create], param: :slug do
        collection do
          get "/:slug/new", action: "new", as: :new
        end
      end
    end

    scope module: :liff, path: :liff, as: :liff do
      get "/(:liff_path)", action: "index"
    end

    scope module: :liff, path: :twliff, as: :twliff do
      get "/(:liff_path)", action: "tw_index"
    end

    scope module: :user_bot, path: :user_bot, as: :user_bot do
      resource :change_log, only: [:update, :show]

      scope module: :users do
        get "/connect(/social_service_user_id/:social_service_user_id)", as: :connect_user, action: "connect" # user sign in
        get "/sign_up(/social_service_user_id/:social_service_user_id)", as: :sign_up, action: "sign_up" # user sign up
        get "(/:locale)/line_sign_up", as: :line_sign_up, action: "line_sign_up" # social user sign up
        get :generate_code
        get :identify_code
        post :create_user
        post :create_shop_profile
        get :check_shop_profile
      end

      resources :schedules, only: [] do
        collection do
          get "mine/:reservation_date(/r/:reservation_id)", to: "schedules#mine", constraints: { reservation_date: /\d{4}-\d{1,2}-\d{1,2}/ }, as: :my_date
          get :mine
        end
      end

      resources :calendars, only: [] do
        collection do
          get "my_working_schedule"
          get "/social_service_user_id/:social_service_user_id", action: "my_working_schedule"
        end
      end

      # business owner scope START
      scope "/owner/(:business_owner_id)" do
        resources :schedules, only: [:index] do
          collection do
            get ":reservation_date(/r/:reservation_id)", to: "schedules#index", constraints: { reservation_date: /\d{4}-\d{1,2}-\d{1,2}/ }, as: :date
            get "/social_service_user_id/:social_service_user_id", action: "index"
          end
        end

        resources :calendars, only: [] do
          collection do
            get "personal_working_schedule"
            get "/social_service_user_id/:social_service_user_id", action: "index"
          end
        end
        namespace :metrics do
          get :dashboard, path: '/'
          get :sale_pages
          get :online_services
          get "/online_services/:id", action: "online_service", as: :online_service, constraints: { id: /\d+/ }

          namespace :sale_pages do
            get :visits
            get :conversions
          end

          namespace :online_services do
            get "/:id/sale_pages_visits", action: :sale_pages_visits, as: :sale_pages_visits
            get "/:id/sale_pages_conversions", action: :sale_pages_conversions, as: :sale_pages_conversions
          end
        end

        resources :broadcasts, only: [:index, :new, :create, :show, :update, :edit] do
          collection do
            get "/new/social_service_user_id/:social_service_user_id", action: "new"
            get "/social_service_user_id/:social_service_user_id", action: "index"
            put :customers_count
          end

          member do
            put :draft
            put :activate
            post :clone
          end
        end

        resources :services, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
          collection do
            get "/new/social_service_user_id/:social_service_user_id", action: "new"
            get "/social_service_user_id/:social_service_user_id", action: "index"
          end

          resources :custom_messages, only: [:index], module: "services" do
            collection do
              get "/:scenario(/:id)", action: "edit_scenario", as: :edit_scenario
            end
          end

          resources :customers, only: [:index, :show], module: :services do
            member do
              post :approve
              delete :cancel
              put :change_expire_at
            end
          end

          resources :chapters, module: :services, only: [:index, :new, :edit, :update, :create, :destroy] do
            collection do
              put :reorder
            end
            resources :lessons, only: [:new, :create, :show, :edit] do
              resources :custom_messages, only: [:index], module: "lessons" do
                collection do
                  get "/:scenario(/:id)", action: "edit_scenario", as: :edit_scenario
                end
              end
            end
          end

          resources :lessons, module: :services, only: [:update, :destroy]

          resources :episodes, module: :services, only: [:index, :edit, :new, :create, :show, :update, :destroy] do
            resources :custom_messages, only: [:index], module: "episodes" do
              collection do
                get "/:scenario(/:id)", action: "edit_scenario", as: :edit_scenario
              end
            end
          end
        end

        resources :sales, only: [:new, :index, :show, :edit, :update, :destroy] do
          collection do
            get "/new/social_service_user_id/:social_service_user_id", action: "new"
            get "/social_service_user_id/:social_service_user_id", action: "index"
          end

          member do
            post :clone
          end
        end

        scope module: :sales, as: :sales, path: :sales do
          resources :booking_pages, only: [:new, :create]
          resources :online_services, only: [:new, :create]
        end

        resources :custom_messages, only: [:destroy] do
          collection do
            put :update
            post :demo
          end
        end

        resources :bookings, only: [:new] do
          collection do
            get "/new/social_service_user_id/:social_service_user_id", action: "new"
            get :available_options
            post :page
          end
        end

        resources :booking_pages do
          collection do
            get "/social_service_user_id/:social_service_user_id", action: "index"
          end

          member do
            delete "/booking_options/:booking_option_id", action: "delete_option", as: :delete_option
            get :preview_modal
            get :edit_booking_options_order
            put :update_booking_options_order
          end

          resources :custom_messages, only: [:index], module: "booking_pages" do
            collection do
              get "/:scenario(/:id)", action: "edit_scenario", as: :edit_scenario
            end
          end
        end

        resources :booking_options do
          collection do
            get "/social_service_user_id/:social_service_user_id", action: "index"
          end

          member do
            delete "/menus/:menu_id", action: "delete_menu", as: :delete_menu
            patch :reorder_menu_priority
          end
        end

        resources :settings, only: [:index] do
          collection do
            get "/social_service_user_id/:social_service_user_id", action: "index"
          end
        end

        namespace :settings do
          resource :line_keyword, only: [] do
            member do
              get :edit_booking_pages
              put :upsert_booking_pages
              get :edit_booking_options
              put :upsert_booking_options
            end
          end
          resource :user_setting, only: [:edit, :update]

          resource :profile, only: %i[show edit update] do
            collection do
              get :company
            end
          end

          resources :plans, only: [:index]
          resources :payments, only: [:index, :create] do
            collection do
              get :refund
              get :downgrade
              put :change_card
            end

            member do
              get :receipt
            end
          end

          resource :stripe, only: %i[show update]
          resource :square, only: %i[show update]

          resource :social_account, only: [:new, :edit, :update] do
            member do
              get :message_api
              get :login_api
              get :webhook_modal
              get :callback_modal
            end

            collection do
              post :reset
            end

            resource :rich_menu, only: [:edit, :create, :destroy]
            resources :social_rich_menus, only: [:index, :new, :edit, :show] do
              collection do
                post :upsert
                get :keyword_rich_menu_size
              end

              member do
                put :current
              end
            end
          end

          resources :business_schedules, only: [] do
            collection do
              put "/shop/:shop_id/update/:wday", action: :update, as: :update
              get :shops
              get "/shop/:shop_id", action: :index, as: :index
              get "/shop/:shop_id/edit/:wday", action: :edit, as: :edit
            end
          end

app/models/chapter.rb
# == Schema Information
#
# Table name: chapters
#
#  id                :bigint           not null, primary key
#  name              :string
#  position          :integer          default(0)
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#  online_service_id :bigint
#
# Indexes
#
#  index_chapters_on_online_service_id  (online_service_id)
#
class Chapter < ApplicationRecord
  belongs_to :online_service
  has_many :lessons, -> { order(position: :asc, id: :asc) }
end

app/controllers/lines/user_bot/metrics/online_services_controller.rb
# frozen_string_literal: true

class Lines::UserBot::Metrics::OnlineServicesController < Lines::UserBotDashboardController
  include ::MetricsHelpers

  def sale_pages_visits
    render json: ::Metrics::SalePagesVisits.run!(
      user: Current.business_owner,
      sale_page_ids: sale_page_ids,
      metric_start_time: metric_start_time,
      demo: params[:demo] == "true"
    )
  end

  def sale_pages_conversions
    render json: ::Metrics::SalePagesConversions.run!(
      user: Current.business_owner,
      sale_page_ids: sale_page_ids,
      online_service_id: params[:id],
      metric_period: metric_period,
      demo: params[:demo] == "true"
    )
  end

  private

  def sale_page_ids
    SalePage.where(product_id: params[:id], product_type: 'OnlineService').pluck(:id)
  end
end

app/controllers/lines/user_bot/sales/online_services_controller.rb
# frozen_string_literal: true

class Lines::UserBot::Sales::OnlineServicesController < Lines::UserBotDashboardController
  def new
    @sale_templates = SaleTemplate.where(locale: Current.business_owner.locale).order("id")

    if sale_page = SalePage.find_by(id: params[:sale_page_id])
      @selected_online_service = OnlineServiceSerializer.new(sale_page.product).attributes_hash
      @selected_template = sale_page.sale_template.attributes.slice("id", "edit_body", "view_body")
      @sale_page = sale_page.serializer.attributes_hash
    elsif service = OnlineService.find_by(slug: params[:slug])
      @selected_online_service = OnlineServiceSerializer.new(service).attributes_hash
    end
  end

  def create
    args = {
      user: Current.business_owner,
      id: params[:id],
      selected_online_service_id: params[:selected_online_service_id],
      selected_template_id: params[:selected_template_id],
      template_variables: params[:template_variables]&.permit!.to_h,
      content: params[:content].permit!.to_h.transform_values! { |v| v.presence },
      staff: params[:staff]&.permit!&.to_h,
      introduction_video_url: params[:introduction_video_url],
      draft: params[:draft]
    }

    args[:selling_price] = params[:selling_price] if params[:selling_price].present?
    args[:normal_price] = params[:normal_price] if params[:normal_price].present?
    args[:selling_end_at] = params[:selling_end_at] if params[:selling_end_at].present?
    args[:quantity] = params[:quantity] if params[:quantity].present?
    args[:monthly_price] = params[:monthly_price] if params[:monthly_price].present?
    args[:yearly_price] = params[:yearly_price] if params[:yearly_price].present?

    if params[:selling_multiple_times_price].present?
      args[:selling_multiple_times_price] = Array.new(
        params[:selling_multiple_times_price][:times].to_i,
        params[:selling_multiple_times_price][:amount].to_i
      )
    end

    outcome = ::Sales::OnlineServices::Create.run(args)

    return_json_response(outcome, { sale_page_id: outcome.result&.slug, redirect_to: lines_user_bot_sales_path})
  end
end

app/controllers/online_services/customer_payments_controller.rb
# frozen_string_literal: true

module OnlineServices
  class CustomerPaymentsController < ::OnlineServicesController
    def new
      @relation = online_service.online_service_customer_relations.where(customer: current_customer).last
      # subscription there is no order_id for each payment
      @price =
        if @relation.online_service.recurring_charge_required?
          @relation.price_details.first
        else
          @relation.price_details.find { |price| price.order_id == params[:order_id] }
        end
    end

    def create
      relation = online_service.online_service_customer_relations.where(customer: current_customer).last

      Customers::StoreStripeCustomer.run!(customer: relation.customer, authorize_token: params[:token])

      outcome =
        if online_service.recurring_charge_required?
          CustomerPayments::SubscribeOnlineService.run(
            online_service_customer_relation: relation
          )
        else
          price = relation.price_details.find { |price| price.order_id == params[:order_id] }

          CustomerPayments::PurchaseOnlineService.run(
            online_service_customer_relation: relation,
            online_service_customer_price: price,
            manual: true
          )
        end

      return_json_response(outcome, {
        redirect_to: customer_status_online_service_path(slug: params[:slug], encrypted_social_service_user_id: params[:encrypted_social_service_user_id])
      })
    end

    def change_card
      outcome = Customers::StoreStripeCustomer.run(customer: current_customer, authorize_token: params[:token])

      return_json_response(outcome, {
        redirect_to: customer_status_online_service_path(slug: params[:slug], encrypted_social_service_user_id: params[:encrypted_social_service_user_id])
      })
    end
  end
end

app/views/online_services/_accessible_service_customer.html.erb
<% if online_service.course_like? %>
  <%= react_component("user_bot/services/online_service_page/course", { course: online_service_hash, lesson_id: params[:lesson_id], lesson_ids: service_member.watched_lesson_ids || [], encrypted_social_service_user_id: params[:encrypted_social_service_user_id] }, { camelize_props: false }) %>
<% elsif online_service.membership? %>
  <%= react_component(
    "user_bot/services/online_service_page/membership",
    {
      membership: online_service_hash,
      no_available_episodes: !online_service.episodes.available.exists?,
      default_episode: episode ? EpisodeSerializer.new(episode).attributes_hash : {},
      done_episode_ids: service_member.watched_episode_ids || []
    },
    { camelize_props: false }
  ) %>
<% else %>
  <%= react_component("user_bot/services/online_service_page", online_service_hash, { camelize_props: false }) %>
<% end %>

app/views/online_services/_available_service_customer.html.erb
<% if online_service.course? %>
  <%= react_component("user_bot/services/online_service_page/course", { course: online_service_hash, lesson_id: params[:lesson_id], lesson_ids: service_member.watched_lesson_ids || [] }, { camelize_props: false }) %>
<% elsif online_service.membership? %>
  <%= react_component(
    "user_bot/services/online_service_page/membership",
    {
      membership: online_service_hash,
      no_available_episodes: !online_service.episodes.available.exists?,
      default_episode: episode ? EpisodeSerializer.new(episode).attributes_hash : {},
      done_episode_ids: service_member.watched_episode_ids || []
    },
    { camelize_props: false }
  ) %>
<% else %>
  <%= react_component("user_bot/services/online_service_page", online_service_hash, { camelize_props: false }) %>
<% end %>

app/views/online_services/_guest.html.erb
<div class="booking-content">
  <%= render "service_header", online_service_hash: online_service_hash %>
  <div class="done-view">
    <h2 class="title">
      <%= online_service_hash[:name] %>
    </h2>
    <h3 class="reminder-mark desc">
      <%= I18n.t("common.only_for_login_user") %>
    </h3>
    <div class="message break-line-content centerize"><%= t("common.read_required_login_user_html") %></div>

    <% if line_login_url(current_owner.social_account, request.url) %>
      <div class="message centerize">
        <h3 class="desc break-line-content"><%= t("common.login_to_watch_html") %></h3>

        <a href="<%= line_login_url(current_owner.social_account, request.url) %>" class="btn line-button with-wording with-logo" data-method="post">
          <%= image_pack_tag "media/assets/booking/btn_login_base.png" %>
          <%= I18n.t("common.line_login_btn_word") %>
        </a>
      </div>
    <% end %>

    <% if current_owner.social_account&.add_friend_url %>
      <div class="message centerize">
        <h3 class="desc break-line-content"><%= t("common.add_friend_to_follow_information_html") %></h3>

        <a href=<%= current_owner.social_account&.add_friend_url %> class="btn line-button with-wording with-logo">
          <%= image_pack_tag "media/assets/booking/btn_login_base.png" %>
          <%= I18n.t("action.add_as_friend") %>
        </a>
      </div>
    <% end %>
  </div>
</div>

app/views/online_services/_inaccessible_service_customer.html.erb
<div class="booking-content">
  <%= render "service_header", online_service_hash: online_service_hash %>
  <div class="done-view">
    <h2 class="title">
      <%= online_service_hash[:name] %>
    </h2>
    <h3 class="reminder-mark desc">
      <%= t("online_service_page.service_unavailable") %>
    </h3>

    <div class="message centerize">
      <div>
        <%= t("online_service_page.service_unavailable_description_html") %>
      </div>
    </div>
  </div>
</div>

app/views/online_services/_inaccessible_service_started_yet_service_customer.html.erb
<div class="booking-content">
  <%= render "service_header", online_service_hash: online_service_hash %>
  <div class="done-view">
    <h2 class="title">
      <%= online_service_hash[:name] %>
    </h2>
    <h3 class="reminder-mark desc">
      <%= t("online_service_page.coming_soon") %>
    </h3>

    <div class="message centerize">
      <div><%= t("online_service_page.start_time_reminder_html", start_date: service_member.start_date_text) %></div>
    </div>
  </div>
</div>

app/views/online_services/_service_header.html.erb
<div class="header border-0 border-b border-solid border-gray-500">
  <div class="header-title-part">
    <% if online_service_hash[:logo_url] %>
      <img class="logo" src='<%= online_service_hash[:logo_url] %>' />
    <% else %>
      <h2><%= online_service_hash[:company_info][:name] %></h2>
    <% end %>
  </div>
</div>

app/views/online_services/_unavailable_customer.html.erb
<div class="booking-content">
  <%= render "service_header", online_service_hash: online_service_hash %>
  <div class="done-view">
    <h2 class="title">
      <%= online_service_hash[:name] %>
    </h2>
    <h3 class="reminder-mark desc">
      <%= I18n.t("common.only_for_login_user") %>
    </h3>
    <div class="message break-line-content centerize"><%= t("common.read_required_login_user_html") %></div>

    <% if current_owner.social_account&.add_friend_url %>
      <div class="message centerize">
        <h3 class="desc break-line-content"><%= t("common.login_add_friend_to_follow_information_html") %></h3>

        <a href=<%= current_owner.social_account&.add_friend_url %> class="btn line-button with-wording with-logo">
          <%= image_pack_tag "media/assets/booking/btn_login_base.png" %>
          <%= I18n.t("booking_page.done.add_friend_btn") %>
        </a>
      </div>
    <% end %>
  </div>
</div>

app/views/online_services/customer_status.html.erb
<div class="service-show form">
  <div class="online-service-header">
    <% if @online_service.company.logo_url %>
      <%= image_tag @online_service.company.logo_url, class: "logo" %>
    <% else %>
      <h2><%= @online_service.company.name %></h2>
    <% end %>
  </div>
  <div class="p6 centerize border-0 border-t border-solid border-gray-500">
    <h1><%= @online_service.name %></h1>
    <h1><%= t("common.usage_status") %></h1>
  </div>

  <%= render "lines/user_bot/services/customers/info" %>
</div>

<%= react_component("shared/stripe_change_card_modal", {
  stripe_key: @online_service.user.stripe_provider&.publishable_key,
  header: @online_service.name,
  pay_btn: I18n.t('plans.actions.change_card'),
  change_card_path: change_card_customer_payments_path(slug: params[:slug], encrypted_social_service_user_id: params[:encrypted_social_service_user_id], format: "json")
},
{ camelize_props: false }
) if @able_to_change_credit_card %>

app/views/online_services/show.html.erb
<%= content_for :meta_tags do %>
  <meta name="robots" content="noindex">
  <meta name="googlebot" content="noindex">
<% end %>

<% if @service_member && @service_member.accessible? %>
  <%= render "online_services/accessible_service_customer", online_service: @online_service, service_member: @service_member, online_service_hash: @online_service_hash, episode: @episode %>
<% elsif @service_member && !@service_member.service_started? %>
  <%= render "online_services/inaccessible_service_started_yet_service_customer", service_member: @service_member, online_service_hash: @online_service_hash %>
<% elsif @service_member && !@service_member.accessible? %>
  <%= render "online_services/inaccessible_service_customer", service_member: @service_member, online_service_hash: @online_service_hash %>
<% elsif current_customer %>
  <%= render "online_services/unavailable_customer", online_service_hash: @online_service_hash %>
<% else %>
  <%= render "online_services/guest", online_service_hash: @online_service_hash %>
<% end %>